name: Cypress Integration Test

on:
  workflow_dispatch:

jobs: 
  cypress-run: 
    runs-on: label2
    strategy:
      fail-fast: false
      matrix:
        containers: [1]
    steps: 
      - name: Checkout 
        uses: actions/checkout@v3 
      - name: Use Node.js
        uses: actions/setup-node@v3 
        with:
          node-version: 18 
      # Install NPM dependencies, cache them correctly
      # and run all Cypress test 
      # sudo apt-get install libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb
      - name: Cypress run
        uses: cypress-io/github-action@v5 
        with:
            spec: "cypress/e2e/**/*.js"
      
    #   - name: Install NPM dependencies
    #     run: npm install
    #   - name: Cypress run
    #     run: npx cypress run 
    
      - name: Upload Screenshots
        uses: actions/upload-artifact@v2
        if: always()
        with:
            name: screenshot
            path: cypress/screenshots/**

      - name: Upload Videos
        uses: actions/upload-artifact@v2
        if: always()
        with:
            name: videos
            path: cypress/videos/**