name: Cypress Integration Test

on:
  workflow_dispatch:

jobs: 
  cypress-run: 
    runs-on: label2
    steps: 
      - name: Checkout 
        uses: actions/checkout@v3 
      - name: Use Node.js
        uses: actions/setup-node@v3 
        with:
          node-version: 18 
      # Install NPM dependencies, cache them correctly
      # and run all Cypress test sudo apt-get update && sudo apt-get install -y libnss3 libgconf-2-4
      - name: Cypress run
        uses: cypress-io/github-action@v5 
        env: 
          DEBUG: '@cypress/github-action'
        with:
          build: npm run cy:run 