name: Test YML

on:
  workflow_dispatch:

jobs:
  # single job that generates and outputs a common id
  prepare:
    runs-on: label1
    steps:
      - name: Generate unique ID
        id: uuid
        # take the current commit + timestamp together
        # the typical value would be something like
        # "sha-5d3fe...35d3-time-1620841214"
        run: |
          $timestamp = [int][double]::Parse((Get-Date -UFormat %s))
          echo "::set-output name=value::sha-$env:GITHUB_SHA-time-$timestamp"

      - name: Print unique ID
        run: echo "generated id ${{ steps.uuid.outputs.value }}"