name: Test YML

on:
  workflow_dispatch:

jobs:
    prepare:
        runs-on: ubuntu-latest
        outputs:
            uuid: ${{ steps.uuid.outputs.value }}
        steps:
          - name: Generate unique ID
            id: uuid
            # take the current commit + timestamp together
            # the typical value would be something like
            # "sha-5d3fe...35d3-time-1620841214"
            run: echo "::set-output name=value::sha-$GITHUB_SHA-time-$(date +"%s")"

          - name: Print unique ID
            run: echo "generated id ${{ steps.uuid.outputs.value }}"
    cypress:
        runs-on: ubuntu-latest
        needs: ["prepare"]
        container:
            image: cypress/browsers:node16.16.0-chrome107-ff107-edge
        steps:
          - name: Checkout repository
            uses: actions/checkout@v2

          - name: Cypress run
            id: cypress-run
            uses: cypress-io/github-action@v4
            with:
                start: npm run
                browser: chrome
                wait-on-timeout: 300
                # config: defaultCommandTimeout=100000,pageLoadTimeout=100000
                # env: grepTags=@smoke @reg
                record: true
                parallel: true
                ci-build-id: ${{ needs.prepare.outputs.uuid }}
                tag: cypressrun
                spec: "cypress/e2e/**/*.js"
