name: Test YML

on:
  workflow_dispatch:

jobs:
  # single job that generates and outputs a common id
  prepare:
    runs-on: label1
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '12'